version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: prokeeep-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@prokeep
      POSTGRESQL_DATABASE: prokeep-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
